# Generated by Django 4.2.2 on 2023-08-31 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elearning', '0005_userprofile_course_instructor_submission_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(null=True, related_name='enrolled_courses', through='elearning.Enrollment', to=settings.AUTH_USER_MODEL),
        ),
    ]
